### ISSUE TITLE
Supported Version - 4.0.9 Support?

### ISSUE THREAD

**Issue by syt-j** [robertcsapo/ciscodnacnetbox#22]
I'm trying to install this on the dockerised version of Netbox. However, I'm running into an issue. When deploying I'm seeing this.

```
[+] Building 15.4s (10/10) FINISHED                                                                                                                               docker:default
 => [netbox internal] load build definition from Dockerfile-Plugins                                                                                                         0.0s
 => => transferring dockerfile: 587B                                                                                                                                        0.0s
 => [netbox internal] load metadata for docker.io/netboxcommunity/netbox:latest                                                                                             0.4s
 => [netbox internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 162B                                                                                                                                           0.0s
 => CACHED [netbox 1/6] FROM docker.io/netboxcommunity/netbox:latest@sha256:dcbe8191f7e24c9440b4f34969c14cefd476706c8f2c7fa220a6714b0bc8b50e                                0.0s
 => [netbox internal] load build context                                                                                                                                    0.0s
 => => transferring context: 314B                                                                                                                                           0.0s
 => [netbox 2/6] COPY ./plugin_requirements.txt /opt/netbox/                                                                                                                0.1s
 => [netbox 3/6] RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /opt/netbox/plugin_requirements.txt                                                    12.0s
 => [netbox 4/6] COPY configuration/configuration.py /etc/netbox/config/configuration.py                                                                                    0.1s
 => [netbox 5/6] COPY configuration/plugins.py /etc/netbox/config/plugins.py                                                                                                0.1s
 => ERROR [netbox 6/6] RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-inp  2.5s
 > [netbox 6/6] RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input:
2.342 Traceback (most recent call last):
2.342   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 255, in fetch_command
2.342 🧬 loaded config '/etc/netbox/config/configuration.py'
2.342 🧬 loaded config '/etc/netbox/config/extra.py'
2.342 🧬 loaded config '/etc/netbox/config/logging.py'
2.342 🧬 loaded config '/etc/netbox/config/plugins.py'
2.344     app_name = commands[subcommand]
2.344                ~~~~~~~~^^^^^^^^^^^^
2.344 KeyError: 'collectstatic'
2.344
2.344 During handling of the above exception, another exception occurred:
2.344
2.344 Traceback (most recent call last):
2.344   File "/opt/netbox/netbox/manage.py", line 10, in <module>
2.344     execute_from_command_line(sys.argv)
2.344   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2.344     utility.execute()
2.344   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
2.344     self.fetch_command(subcommand).run_from_argv(self.argv)
2.345     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.345   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 262, in fetch_command
2.345     settings.INSTALLED_APPS
2.345   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in __getattr__
2.346     self._setup(name)
2.346   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in _setup
2.346     self._wrapped = Settings(settings_module)
2.346                     ^^^^^^^^^^^^^^^^^^^^^^^^^
2.346   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
2.346     mod = importlib.import_module(self.SETTINGS_MODULE)
2.346           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.346   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
2.347     return _bootstrap._gcd_import(name[level:], package, level)
2.347            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.347   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2.347   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2.347   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2.347   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2.347   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2.347   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2.347   File "/opt/netbox/netbox/netbox/settings.py", line 785, in <module>
2.349     raise e
2.349   File "/opt/netbox/netbox/netbox/settings.py", line 778, in <module>
2.349     plugin = importlib.import_module(plugin_name)
2.349              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.349   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
2.349     return _bootstrap._gcd_import(name[level:], package, level)
2.350            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.350   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2.350   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2.350   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2.350   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2.350   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2.350   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2.350   File "/opt/netbox/venv/lib/python3.11/site-packages/ciscodnacnetbox/__init__.py", line 1, in <module>
2.350     from extras.plugins import PluginConfig
2.350 ModuleNotFoundError: No module named 'extras.plugins'
------
failed to solve: process "/bin/sh -c SECRET_KEY=\"dummydummydummydummydummydummydummydummydummydummy\" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --n       

```

I am currently running versions 

![image](https://github.com/user-attachments/assets/47041d61-bfd0-422e-bde4-e8700283cc32)

I have the plugins set correctly in the requirements files and in the plugins configuration. Am I missing something?

```
xxxxx@xxxxxx:/docker/projects/netbox-docker$ cat plugin_requirements.txt
ciscodnacnetbox
netbox-secrets
netbox_ipcalculator
netbox-inventory
netbox-plugin-dns
netbox-documents
requests
xmltodict
pymssql
```

```python
xxxxxx@xxxxxx:/docker/projects/netbox-docker/configuration$ cat plugins.py
# Add your plugins and plugin settings here.
# Of course uncomment this file out.

# To learn how to build images with your required plugins
# See https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

PLUGINS = [
    "netbox_secrets",
    "netbox_dns",
    "netbox_ipcalculator",
    "netbox_inventory",
    "netbox_documents",
    "ciscodnacnetbox",
]

# PLUGINS_CONFIG = {
#   "netbox_bgp": {
#     ADD YOUR SETTINGS HERE
#   }
# }
```

**Comment by robertcsapo** [comment]
This is related to #21 , as NetBox 4.x would require significant code change.
